ruleset {
  AbstractClassName
  AbstractClassWithPublicConstructor
  AddEmptyString
  AssertWithinFinallyBlock
  AssignCollectionSort
  AssignCollectionUnique
  AssignmentInConditional
  AssignmentToStaticFieldFromInstanceMethod
  BigDecimalInstantiation
  BitwiseOperatorInConditional
  BlankLineBeforePackage
  BlockEndsWithBlankLine
  BlockStartsWithBlankLine
  BooleanGetBoolean
  BooleanMethodReturnsNull
  BracesForClass
  BracesForForLoop
  BracesForIfElse
  BracesForMethod
  BracesForTryCatchFinally
  BrokenNullCheck
  BrokenOddnessCheck
  BuilderMethodWithSideEffects
  BusyWait
  CatchArrayIndexOutOfBoundsException
  CatchError
  CatchException
  CatchIllegalMonitorStateException
  CatchIndexOutOfBoundsException
  CatchNullPointerException
  CatchRuntimeException
  CatchThrowable
  ClassForName
  ClassName
  ClassNameSameAsFilename
  ClassNameSameAsSuperclass
  ClassSize
  CloneableWithoutClone
  CloseWithoutCloseable
  ClosureAsLastMethodParameter
  ClosureStatementOnOpeningLineOfMultipleLineClosure
  CollectAllIsDeprecated
  CompareToWithoutComparable
  ComparisonOfTwoConstants
  ComparisonWithSelf
  ConfusingClassNamedException
  ConfusingMethodName
  ConfusingMultipleReturns
  ConfusingTernary
  ConsecutiveBlankLines
  ConsecutiveLiteralAppends
  ConsecutiveStringConcatenation
  ConstantAssertExpression
  ConstantIfExpression
  ConstantTernaryExpression
  ConstantsOnlyInterface
  CouldBeElvis
  CouldBeSwitchStatement
  DeadCode
  DirectConnectionManagement
  DoubleCheckedLocking
  DoubleNegative
  DuplicateCaseStatement
  DuplicateImport
  DuplicateListLiteral
  DuplicateMapKey
  DuplicateMapLiteral
  DuplicateNumberLiteral
  DuplicateSetValue
  DuplicateStringLiteral
  ElseBlockBraces
  EmptyCatchBlock
  EmptyClass
  EmptyElseBlock
  EmptyFinallyBlock
  EmptyForStatement
  EmptyIfStatement
  EmptyInstanceInitializer
  EmptyMethod
  EmptyMethodInAbstractClass
  EmptyStaticInitializer
  EmptySwitchStatement
  EmptySynchronizedStatement
  EmptyTryBlock
  EmptyWhileStatement
  EnumCustomSerializationIgnored
  EqualsAndHashCode
  EqualsOverloaded
  ExceptionExtendsError
  ExceptionExtendsThrowable
  ExceptionNotThrown
  ExplicitArrayListInstantiation
  ExplicitCallToAndMethod
  ExplicitCallToCompareToMethod
  ExplicitCallToDivMethod
  ExplicitCallToEqualsMethod
  ExplicitCallToGetAtMethod
  ExplicitCallToLeftShiftMethod
  ExplicitCallToMinusMethod
  ExplicitCallToModMethod
  ExplicitCallToMultiplyMethod
  ExplicitCallToOrMethod
  ExplicitCallToPlusMethod
  ExplicitCallToPowerMethod
  ExplicitCallToRightShiftMethod
  ExplicitCallToXorMethod
  ExplicitGarbageCollection
  ExplicitHashMapInstantiation
  ExplicitHashSetInstantiation
  ExplicitLinkedHashMapInstantiation
  ExplicitLinkedListInstantiation
  ExplicitStackInstantiation
  ExplicitTreeSetInstantiation
  FactoryMethodName
  FieldName
  FieldTypeRequired
  FileCreateTempFile
  FileEndsWithoutNewline
  FinalClassWithProtectedMember
  ForLoopShouldBeWhileLoop
  ForStatementBraces
  GStringAsMapKey
  GStringExpressionWithinString
  GetterMethodCouldBeProperty
  GroovyLangImmutable
  HardCodedWindowsFileSeparator
  HardCodedWindowsRootDirectory
  HashtableIsObsolete
  IfStatementBraces
  IfStatementCouldBeTernary
  IllegalClassMember
  IllegalClassReference
  IllegalPackageReference
  IllegalRegex
  IllegalString
  IllegalSubclass
  ImplementationAsType
  ImportFromSamePackage
  ImportFromSunPackages
  InconsistentPropertyLocking
  InconsistentPropertySynchronization
  Indentation { spacesPerIndentLevel = 2 }
  InsecureRandom
  Instanceof
  IntegerGetInteger
  InterfaceName
  InterfaceNameSameAsSuperInterface
  InvertedCondition
  InvertedIfElse
  JavaIoPackageAccess
  JdbcConnectionReference
  JdbcResultSetReference
  JdbcStatementReference
  LineLength
  LocaleSetDefault
  LoggerForDifferentClass
  LoggerWithWrongModifiers
  LoggingSwallowsStacktrace
  LongLiteralWithLowerCaseL
  MethodParameterTypeRequired
  MethodSize
  MisorderedStaticImports { comesBefore = false }
  MissingBlankLineAfterImports
  MissingBlankLineAfterPackage
  MissingNewInThrowStatement
  MultipleLoggers
  MultipleUnaryOperators
  NestedBlockDepth
  NestedForLoop
  NestedSynchronization
  NoDef(enabled: false)
  NoJavaUtilDate
  NoTabCharacter
  NoWildcardImports
  NonFinalPublicField
  NonFinalSubclassOfSensitiveInterface
  ObjectFinalize
  ObjectOverrideMisspelledMethodName
  PackageName
  PackageNameMatchesFilePath
  ParameterCount
  ParameterName
  ParameterReassignment
  PrintStackTrace
  Println
  PrivateFieldCouldBeFinal
  PublicFinalizeMethod
  PublicInstanceField
  PublicMethodsBeforeNonPublicMethods(enabled: false)
  RandomDoubleCoercedToZero
  RemoveAllOnSelf
  RequiredRegex
  RequiredString
  ReturnFromFinallyBlock
  ReturnNullFromCatchBlock
  ReturnsNullInsteadOfEmptyArray
  ReturnsNullInsteadOfEmptyCollection
  SerialPersistentFields
  SerialVersionUID
  SerializableClassMustDefineSerialVersionUID
  SimpleDateFormatMissingLocale
  SpaceAfterCatch
  SpaceAfterClosingBrace
  SpaceAfterComma
  SpaceAfterFor
  SpaceAfterIf
  SpaceAfterOpeningBrace
  SpaceAfterSemicolon
  SpaceAfterSwitch
  SpaceAfterWhile
  SpaceAroundClosureArrow
  SpaceAroundMapEntryColon { characterAfterColonRegex = / / }
  SpaceAroundOperator
  SpaceBeforeClosingBrace
  SpaceBeforeOpeningBrace
  StatelessClass
  StatelessSingleton
  StaticCalendarField
  StaticConnection
  StaticDateFormatField
  StaticFieldsBeforeInstanceFields
  StaticMatcherField
  StaticMethodsBeforeInstanceMethods(enabled: false)
  StaticSimpleDateFormatField
  SwallowThreadDeath
  SynchronizedMethod
  SynchronizedOnBoxedPrimitive
  SynchronizedOnGetClass
  SynchronizedOnReentrantLock
  SynchronizedOnString
  SynchronizedOnThis
  SynchronizedReadObjectMethod
  SystemErrPrint
  SystemExit
  SystemOutPrint
  SystemRunFinalizersOnExit
  TernaryCouldBeElvis
  ThisReferenceEscapesConstructor
  ThreadGroup
  ThreadLocalNotStaticFinal
  ThreadYield
  ThrowError
  ThrowException
  ThrowExceptionFromFinallyBlock
  ThrowNullPointerException
  ThrowRuntimeException
  ThrowThrowable
  ToStringReturnsNull
  TrailingComma
  TrailingWhitespace
  UnnecessaryBigDecimalInstantiation
  UnnecessaryBigIntegerInstantiation
  UnnecessaryBooleanExpression
  UnnecessaryBooleanInstantiation
  UnnecessaryCallForLastElement
  UnnecessaryCallToSubstring
  UnnecessaryCast
  UnnecessaryCatchBlock
  UnnecessaryCollectCall
  UnnecessaryCollectionCall
  UnnecessaryConstructor
  UnnecessaryDefInFieldDeclaration
  UnnecessaryDefInMethodDeclaration
  UnnecessaryDefInVariableDeclaration
  UnnecessaryDotClass
  UnnecessaryDoubleInstantiation
  UnnecessaryElseStatement
  UnnecessaryFinalOnPrivateMethod
  UnnecessaryFloatInstantiation
  UnnecessaryGString
  UnnecessaryGetter
  UnnecessaryGroovyImport
  UnnecessaryIfStatement
  UnnecessaryInstanceOfCheck
  UnnecessaryInstantiationToGetClass
  UnnecessaryIntegerInstantiation
  UnnecessaryLongInstantiation
  UnnecessaryModOne
  UnnecessaryNullCheck
  UnnecessaryNullCheckBeforeInstanceOf
  UnnecessaryObjectReferences
  UnnecessaryOverridingMethod
  UnnecessaryPackageReference
  UnnecessaryParenthesesForMethodCallWithClosure
  UnnecessaryPublicModifier
  UnnecessaryReturnKeyword
  UnnecessarySafeNavigationOperator
  UnnecessarySelfAssignment
  UnnecessarySemicolon
  UnnecessarySetter
  UnnecessaryStringInstantiation
  UnnecessarySubstring
  UnnecessaryTernaryExpression
  UnnecessaryToString
  UnnecessaryTransientModifier
  UnsafeArrayDeclaration
  UnsafeImplementationAsMap
  UnusedArray
  UnusedImport
  UnusedMethodParameter
  UnusedObject
  UnusedPrivateField
  UnusedPrivateMethod
  UnusedPrivateMethodParameter
  UnusedVariable
  UseCollectMany
  UseCollectNested
  UseOfNotifyMethod
  VariableTypeRequired(enabled: false)
  VectorIsObsolete
  VolatileArrayField
  VolatileLongOrDoubleField
  WaitOutsideOfWhileLoop
  WhileStatementBraces

  // property names for onbase classes are beyond my control
  PropertyName { doNotApplyToClassNames = "edu.hawaii.its.fob.db.onbase.*" }
}
